### ISSUE TITLE
Rebuilt BDAT is incorrect size and does not boot

### ISSUE THREAD

**Issue by SoulBlast35** [roccodev/bdat-rs#12]
Hi, wanted to know if Im doing something wrong or if there's an issue here. I was extracting common.bdat from Xenoblade 2 to make edits, but when I repacked the bdat, the file size had changed from 5184 KB to 5027 KB. Additionally, when attempting to load from this edited file via modded Switch or Ryujinx, Xenoblade 2 would hang on a black screen.

EDIT: Comparing the two extracted BDAT's with WinMerge, it seems that the Packing process is not only starting some data tables at id 0 instead of 1, its truncating a bunch of id numbers such as in the Blade Table.

**Comment by roccodev** [comment]
Hi, thanks for reporting the issue!

The ID issue should be fixed in 03a4277. Could you try the files from that build? You can find them at the bottom of this page: https://github.com/roccodev/bdat-rs/actions/runs/11056487767

The file size isn't really a concern because the converter doesn't aim to be binary-compatible with the original, I think it's missing some alignments here and there.

**Comment by SoulBlast35** [comment]
Working perfectly, thanks a ton!
