### ISSUE TITLE
toolset not in workspace and not runnable from repo root

### ISSUE THREAD

**Issue by ScanMountGoat** [RoccoDev/bdat-rs#8]
I would like to be able to run the CLI tool with `cargo run -p bdat-toolset` and check all code with `cargo check`. I can always cd into the toolset directory, but that creates multiple target directories.

**Comment by RoccoDev** [comment]
Gotcha! 854ddfd adds the toolset crate to the workspace.

I was concerned at first about having Cargo.lock in the lib root, but as it turns out, clients ignore it for libraries even if present.

On another note, I'm making some API changes in a separate branch, so some 0.4 features might not work in 0.5. These changes mostly come from my use of the library in Recordkeeper and the enemy compendium, so they boil down to allowing the library to be used more ergonomically with XC3 BDATs at the expense of some conveniences for multi-version support. If you have some other use cases you think the library could be improved for, then please do tell.
